### ISSUE TITLE
stuck after 21 minutes

### ISSUE THREAD

**Issue by geekabit-nl** [asivery/webminidisc#2]
I have many discs containing live recordings with a single long track. Using the new download functionality I tried tried to copy those disks over to my pc. But download always hangs at 21 minutes. I can reproduce this issue on 20+ disks. Shorter tracks work fine.

I used the WebMD version on https://web.minidisc.wiki/
Console log is attached.

Recorder: MZ-R30, analog in, atrac1
Player: MZ-N510 (firmware 1.6)
Browser: Chromium Version 100.0.4896.127 (Official Build) built on Debian bookworm/sid, running on Debian bookworm/sid (64-bit)
WebMD: Version #ae228dd (19694 diff-lines ahead) built on Mon Jul 4 23:00:46 UTC 2022

[log.txt](https://github.com/asivery/webminidisc/files/9045737/log.txt)

**Comment by thinkbrown** [comment]
good news/bad news, it's reproducible on my MZ-NE410.

**Comment by asivery** [comment]
@geekabit-nl I have managed to reproduced the issue as well, thanks for reporting it.

**Comment by asivery** [comment]
@geekabit-nl I have updated webminidisc, please let me know if it works now.

**Comment by geekabit-nl** [comment]
Problem is solved. Downloading works fine now on all longer tracks. Thanks!

**Comment by thinkbrown** [comment]
These logs are both what I'd expect to see from trying to dump a dirty/damaged disc. The current dumping method is very sensitive to read errors and doesn't have a way to handle them gracefully.

Essentially what's happening is the software is reading a sector and correctly detecting that the sector isn't valid due to the read error. It's then jumping to the last good sector read and trying continue reading, ad infinitum. 

As far as the version number in the log goes, you're absolutely correct: probably be a good idea.

**Comment by geekabit-nl** [comment]
Okay, that's clear. I'll store the disks for the day those read errors are recoverable. Thanks!
