### ISSUE TITLE
Feature / help request: importing (perhaps local) playlists to WebMiniDisc Pro

### ISSUE THREAD

**Issue by hg-ts** [asivery/webminidisc#24]
I apologize in advance if this has been covered or is outside the scope of the project. I have tried looking for info elsewhere, but it seems there is little to no info available.

I am wondering if there is a way to import a playlist into WebMiniDisc? I have a lot of playlists on Spotify that I want to burn to MD, but I would like to avoid the hassle of either real-time recording and manual editing or having to manually rebuild the playlist from local files.

I am OK with being forced to use local files, as I have most of my Spotify library stored locally as well. I am totally fine with performing the Spotify->.m3u step through other means. But I can't figure out if there's a way to drop an .m3u or similar file into WebMiniDisc. I realize it may be a pretty complicated ask, since it might require WebMD to be able to map my entire library and not just the specific file locations I want to record.

Any help would be appreciated, including possible workarounds. The same goes for any comment as to whether there's any hope of having this feature added down the road.

Cheers, and thanks for maintaining this wonderful piece of software!

**Comment by asivery** [comment]
Hello there @hg-ts,

A lot of people asked me about playlist support - M3U or CUE, and for now I am still evaluating ways in which it could be implemented. Because Web Minidisc Pro is a webapp, there aren't a lot of ways in which it could be done - browsers are somewhat restrictive when it comes to accessing local files.

For now, the only solution I can propose to you, is to convert the M3U files to CUE files, and burn them with [netmd-wizard](https://github.com/Jo2003/cd2netmd_gui). This app should let you accomplish exactly what you're looking for :)
