### ISSUE TITLE
"Rename Disc" issues with certain characters

### ISSUE THREAD

**Issue by CH23-** [asivery/webminidisc#38]
When adding the name 'Röyksopp', this is then displayed as 'Roeyksopp' on MZ-N10.

Another naming issue occurred where album title contains 2 slashes. this is replaced by a space and single slash.

**Comment by asivery** [comment]
Hello @CH23- !
Unfortunately MiniDisc only supports ASCII characters as track / disc titles. This is why your title got normalized to ASCII so that the device could read it.
As for the title containing two slashes one after another - MiniDiscs use `//` to denote a new group, as groups are also stored in the track title. This is why WebMinidisc adjusted that as well - so that it doesn't interfere with groups.
